### ISSUE TITLE
Please properly tag releases

### ISSUE THREAD

**Issue by SnarkBoojum** [chaijs/check-error#17]
Hi,

npmjs.com says the latest version is 1.0.2, but according to this repository, the last official one is 1.0.1.

Could you properly tag this release?

Thanks

**Comment by keithamus** [comment]
Hey @SnarkBoojum thanks for the issue

Looks like our CI isnt tagging these properly. I've manually added it https://github.com/chaijs/check-error/releases/tag/v1.0.2. Thanks for pointing it out
