### ISSUE TITLE
Tag `2.0.0` release

### ISSUE THREAD

**Issue by voxpelli** [chaijs/check-error#48]
The `2.0.0` release is found on npm: https://www.npmjs.com/package/check-error/v/2.0.0

But here on GitHub there is no tag for it: https://github.com/chaijs/check-error/tags

 And neither no commit mentioning the release, latest being merge of #46: [Use web test runner instead of karma](https://github.com/chaijs/check-error/commit/fd56c9ea3ddb4c820f5151565dcd28a30694a151)
 
 (This is a follow up to https://github.com/chaijs/chai/pull/1528#issuecomment-1646236724)

**Comment by keithamus** [comment]
https://github.com/chaijs/check-error/releases/tag/v2.0.0
